name: "nakama"
data_dir: "/nakama/data"

log:
  level: "INFO"
  stdout: true
  file: "/nakama/logs/nakama.log"

database:
  address: "postgres://postgres:C24T7gH2wAcwrG6ZDdpR@aicart-prod.c8t8osoe03oe.us-east-1.rds.amazonaws.com:5432/nakama_database?sslmode=require"

socket:
  server_address: "0.0.0.0"
  server_port: 7349
  server_protocol: "tcp"

server:
  http_address: "0.0.0.0"
  http_port: 7350

console:
  address: "0.0.0.0"
  port: 7351
  username: "admin"
  password: "password"

session:
  token_expiry_sec: 7200

runtime:
  js_path: "/nakama/data/modules"
  lua_path: "/nakama/data/modules/lua"
  http_key: "defaultkey"
  http_signature_key: "defaultsignaturekey"

metrics:
  reporting_freq_sec: 60
